### ISSUE TITLE
Add Various HTML And Css Styled Web Pages

### ISSUE THREAD

**Issue by dikshantmali** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#1]
Anyone can add various HTML CSS design webpages including the registration form, various pages with their name like your_name.html. Anyone who has eager to learn can contribute to this repository. This repo will help so many people to learn basic HTML and CSS concept who are new to web technology.

**Comment by aditimaurya** [comment]
Hey, what kind of webpage you wanted?

**Comment by dikshantmali** [comment]
@aditimaurya any type of html-css web page depends on you. It can be anything like simple form, adding parallax so that people can understand how to use parallax, adding flex box, adding navbar, adding footer for website like that. Anyone can add anything written in HTML CSS so that the people who are beginner can learn let say how to add navbar, how to generate shadow for an image anything like that

**Comment by alkatrivedi** [comment]
I would like to work it. May I?

**Comment by dikshantmali** [comment]
@alkatrivedi sure 🙂🙂 go ahead

**Comment by alkatrivedi** [comment]
On it. Thank you!

**Comment by aditimaurya** [comment]
@dikshantmali  ig multiple people can work on this , right? Like there's always a scope of better designs. Once @alkatrivedi  will prepare a structure I'd like to refine it or add some more designs if there's no problem with that. :) Do let me know please.

**Comment by dikshantmali** [comment]
@aditimaurya do whatever you want. Just contribute And contribute dont worry I will merge each and every pull request

**Comment by alkatrivedi** [comment]
@dikshantmali can you please review my PR #2. Please do let me know whether it's fine or not. Thank you:)

**Comment by mnrazablog** [comment]
I would like to work on this issue

**Comment by dikshantmali** [comment]
@mnrazablog go ahead :)

**Comment by AlacritousCreature** [comment]
Hey! I added a lovely Loader for Webpages. Please review it.

**Comment by kashishvir** [comment]
I believe it's a good start for beginners.  I enjoyed working on it! Please have a look on my work. 
Thank You!

**Comment by anisha282000** [comment]
Hey, @dikshantmali I would like to work on this issue.
May I?

**Comment by dikshantmali** [comment]
@anisha282000 sure go ahead :)

**Comment by anisha282000** [comment]
@dikshantmali webpages should be responsive?

**Comment by dikshantmali** [comment]
@anisha282000 depends on you :) if it is responsive add responsive with your folder name

**Comment by hmmonotone** [comment]
May I work on this issue?

**Comment by hmmonotone** [comment]
I would add a HTML and CSS based Information page about myself

**Comment by dikshantmali** [comment]
@hmmonotone create a information detail page with random detail it would be very helpful for others

**Comment by hmmonotone** [comment]
@dikshantmali I have just added the files and also commented the deployed version of it. Please Check

**Comment by dikshantmali** [comment]
@hmmonotone Good work.

**Comment by shikhargupta-in** [comment]
Hi, @dikshantmali 
Can I add some styled webpage?

**Comment by soumakpoddar** [comment]
hi, @dikshantmali can I contribute now???Is the request open??

**Comment by shristi54** [comment]
Can i have this issue to increase it's proficiency?

**Comment by dikshantmali** [comment]
@shristi54 just go and make PR. If valid I will merge no need to ask again and again for each issue :)

**Comment by shristi54** [comment]
what about login.html file? I have made some changes, please check!  :)

**Comment by dikshantmali** [comment]
@shristi54 I have already merge your modified login file :)

**Comment by PRASHANT-SAJWAN** [comment]
May I work on this issue?

**Comment by knightspore** [comment]
Hey, I created an example for one of the things I struggled the most with as a beginner with CSS. You can [find the PR here](https://github.com/dikshantmali/Hacktoberfest2020-HTML-CSS-WEB/pull/60), thanks!

**Comment by ritinharizzieri** [comment]
I would like to work on this issue

**Comment by Anushree176** [comment]
I would like to work. May I?

**Comment by devarshidoshi** [comment]
Can I Add My CSS Arts Here??

**Comment by Kelechi-Eluagu** [comment]
Please assign me so I can also contribute

**Comment by Apoorva110032** [comment]
I would like to work on this. May I?

**Comment by Kelechi-Eluagu** [comment]
I would love to contribute

**Comment by Sparroww77** [comment]
I would like to work on this

**Comment by ISHJOT15** [comment]
Added two web pages a resume template and a registration form.... Please check

**Comment by ISHJOT15** [comment]
#171

**Comment by ISHJOT15** [comment]
#181

**Comment by aritrochakraborty29** [comment]
Want to work on it..
can you please assign me..?

**Comment by ISHJOT15** [comment]
> Anyone can add various HTML CSS design webpages including the registration form, various pages with their name like your_name.html. Anyone who has eager to learn can contribute to this repository. This repo will help so many people to learn basic HTML and CSS concept who are new to web technology.

#181
