### ISSUE TITLE
Add Animated Scripts To These Repositories

### ISSUE THREAD

**Issue by dikshantmali** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#11]
add animation to any webpage that you create. The requirement is to make people learn how they can use animation with javascript or normal CSS on hover or anything like that.

**Comment by Guilleo03** [comment]
what kind of webpage do you mean?

**Comment by dikshantmali** [comment]
any thing :) you can check master code to know more about it.

**Comment by Guilleo03** [comment]
thanks im gonna check

**Comment by dikshantmali** [comment]
@Guilleo03 go ahead and contribute to this awesome beginner-friendly repo

**Comment by Guilleo03** [comment]
thanks! im gonna try. Im new on github open source projects

**Comment by alessandraburckhalter** [comment]
Hey there! Can I work on this?

**Comment by dikshantmali** [comment]
@alessandraburckhalter sure :)

**Comment by kashishvir** [comment]
hey! can I work on this issue?

**Comment by aryanthakre** [comment]
Can I work ?

**Comment by dikshantmali** [comment]
@aryanthakre go ahead

**Comment by Easyvipin** [comment]
#81  added auth-form animated layout

**Comment by alessandraburckhalter** [comment]
added animation to calculator file #74

**Comment by jessadakronb** [comment]
hey! can I work on this issue?

**Comment by aritrochakraborty29** [comment]
Want to work on it..
can you please assign me..?
