### ISSUE TITLE
Modify the already existing code in respective folder

### ISSUE THREAD

**Issue by dikshantmali** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#12]

**Comment by pr-jli** [comment]
hey can I work on this issue?

**Comment by dikshantmali** [comment]
@pr-jli sure :) I want someone to modify the Readme document. Go ahead and make it awesome

**Comment by pr-jli** [comment]
#19  I have made a few changes.

**Comment by dikshantmali** [comment]
Thanks @pr-jli for your contribution. You can make more PR if you want to add something

**Comment by shristi54** [comment]
can i get this issue? Please assign me if possible

**Comment by dikshantmali** [comment]
@shristi54 go ahead and fix some problem :) I just you to check each and every code if you encounter any problem immediately generate PR

**Comment by PRASHANT-SAJWAN** [comment]
can I add and modify HTML, css, js files of the existing codes??

**Comment by shweta-laha** [comment]
hey! 
I want to contribute please assign me if possible.

**Comment by Kelechi-Eluagu** [comment]
I hope I can contribute
