### ISSUE TITLE
add style to Error404

### ISSUE THREAD

**Issue by MallikarjunHt** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#20]
make error 404 as red and make it blik
![Screenshot from 2020-10-01 09-18-28](https://user-images.githubusercontent.com/40291553/94763148-1e7fcf80-03c7-11eb-8ce1-1d4b9de00871.png)

**Comment by dikshantmali** [comment]
@MallikarjunHt  If you have modified it then make a PR for it.

**Comment by MallikarjunHt** [comment]
Thanks for accepting pull request 
#23
