### ISSUE TITLE
issue 4 : Create Responsive Page Shown As Below With Pure HTML, CSS 

### ISSUE THREAD

**Issue by dikshantmali** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#61]
You can Add offline bootstrap framework for making it responsive.

**Comment by dikshantmali** [comment]
The image is shown below : )
![WhatsApp Image 2020-10-01 at 8 03 19 PM](https://user-images.githubusercontent.com/47856779/94823922-09845a00-0422-11eb-91ac-2fca1f42c355.jpeg)

**Comment by knowyours** [comment]
May I know what the Image slider should do?

**Comment by dikshantmali** [comment]
@knowyours you can take help from below link and add any random image. 
https://www.w3schools.com/howto/howto_js_slideshow.asp

**Comment by knowyours** [comment]
And the backround gradients??

**Comment by dikshantmali** [comment]
As per your choice. Main moto is that the design should be same to that image.

**Comment by knowyours** [comment]
Thanks for assigning. The elements don't have to be functional right? Just the visual layout is enough right?

**Comment by dikshantmali** [comment]
@knowyours right only functional layout keep it simple no need to add any animation

**Comment by knowyours** [comment]
> @knowyours right no need of functional layout keep it simple no need to add any animation. Please add "issue no. 4 resolved" in your PR title

Okay 👍

**Comment by knowyours** [comment]
@dikshantmali Hello, please check if the above files suffice the requirement.
