### ISSUE TITLE
Issue 5 : Create Responsive  footer for web as shown below 

### ISSUE THREAD

**Issue by dikshantmali** [dikshantmali/Hacktoberfest2020-HTML-CSS-WEB#84]
Create a footer with a black background as shown below  :)

**Comment by dikshantmali** [comment]
![WhatsApp Image 2020-10-01 at 8 31 37 PM](https://user-images.githubusercontent.com/47856779/94879111-ed61d680-047c-11eb-9b81-36cd0acbe999.jpeg)

**Comment by knowyours** [comment]
@dikshantmali Can I take this up?

**Comment by dikshantmali** [comment]
@knowyours sure :) I want you to update the previous work that you have done add some stylish responsive cards instead of those blank cards that you put in your previous work. Also make the website in 100% width. You can found your previous work in Gratis directory

**Comment by dikshantmali** [comment]
Also add this footer to that Gratis directory. With footer.html name

**Comment by soumakpoddar** [comment]
I can give it a shot.....

**Comment by dikshantmali** [comment]
@soumakpoddar go ahead read the above comment you will get the idea what work we need to do so that other can use it

**Comment by knowyours** [comment]
@dikshantmali Yes sure, I'll give that a look 👍

**Comment by saiharsha-22** [comment]
@dikshantmali I have added a footer in the graits folder can you please check it once. And I have sent a pull request.
Added a Footer #86
![Screenshot (400)](https://user-images.githubusercontent.com/61947484/94886809-1a6cb400-0492-11eb-9741-5738d9b09110.png)

**Comment by dikshantmali** [comment]
> @dikshantmali Yes sure, I'll give that a look +1

@knowyours please don't spend a lot of time in this project. what I think is doing very hard work is useless so if you don't make it, that is also good. Please be relax, chill and if you love then only contribute. I don't want to add any burden on your shoulder. Open source contribution is all about learning so just learn :100:

**Comment by knowyours** [comment]
> > @dikshantmali Yes sure, I'll give that a look +1
> 
> @knowyours please don't spend a lot of time in this project. what I think is doing very hard work is useless so if you don't make it, that is also good. Please be relax, chill and if you love then only contribute. I don't want to add any burden on your shoulder. Open source contribution is all about learning so just learn 💯

Thanks for that message. Is this issue already solved by another PR? If so, probably I can stop working further on this issue and wait for another one

**Comment by dikshantmali** [comment]
@knowyours if you want to work then you can I will merge your PR. It is not about good and bad it is about contribution. each and every contribution I am merging that is why I have generated issue to resolve already existing code.

**Comment by dineshsy** [comment]
is this issue still alive?
